FROM node:16-alpine as BUILD_IMAGE
WORKDIR /usr/app

RUN apk add --update \
    && apk add --no-cache ca-certificates \
    && apk add --no-cache --virtual .build-deps curl bash

RUN curl -L https://yarnpkg.com/install.sh | bash
COPY package.json tsconfig.base.json ./
COPY ./packages/. packages/
RUN cd packages/common && yarn install