version: '3.7'
services:
    base:
        image: memestro/base
        scale: 0
        build:
            context: ../../
            dockerfile: ./docker/Dockerfile.base
    api:
        container_name: MEMESTRO_API
        restart: unless-stopped
        depends_on:
            - mongo
        env_file:
          - ../../.env
        networks:
            - main-network
    reverse_proxy:
        container_name: MEMESTRO_REVERSE_PROXY
        image: 'caddy:alpine'
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - ../caddy/Caddyfile:/etc/caddy/Caddyfile
        depends_on:
          - api
        networks:
            - main-network

volumes:
  memestro-mongo-db-data:
networks:
    main-network:
        driver: bridge