version: '3.7'
services:
    base:
        image: memestro/base
        scale: 0
        build:
            context: ../../
            dockerfile: ./docker/Dockerfile.base
    api_base:
        image: memestro/api_base
        scale: 0
        build:
            context: ../../
            dockerfile: ./docker/api/Dockerfile.base
        depends_on:
            - base
    api:
        container_name: MEMESTRO_API
        restart: unless-stopped
        depends_on:
            - mongo
            - api_base
    mongo:
        container_name: MEMESTRO_MONGO_DB
        image: mongo
        restart: unless-stopped
        volumes:
            - 'memestro-mongo-db-data:/data/db'

volumes:
  memestro-mongo-db-data: