version: '3.7'
services:
    api:
        build:
            context: ../../
            dockerfile: ./docker/api/Dockerfile
        environment:
            MONGO_URL: mongodb://mongo:27017/dev
            JWT_KEY: thisisatestkey
            PORT: 4327
            NODE_ENV: development
        volumes:
            - '../../services/api:/usr/app/services/api'
        command: ["yarn", "run", "dev"]
    mongo:
        container_name: MEMESTRO_MONGO_DB
        image: mongo
        restart: unless-stopped
        volumes:
            - 'memestro-mongo-db-data:/data/db'
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_DATABASE=dev
        networks:
            - main-network

